<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVKbZuf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVKbZuf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVKbZuf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVKbZuf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXVKbZuf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XVKbZuf',
    'container.build_id' => 'bf8da48d',
    'container.build_time' => 1559316430,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVKbZuf');
